### ISSUE TITLE
When build, files are also generated into the `public/` folder.

### ISSUE THREAD

**Issue by Jeremboo** [ACP-CODE/astro-favicons#6]
Hi,

Thanks a lot for this plugin it helps a lot! 
There is just one thing that makes me curious. Is there a reason why the files are generated into `/dist` but also in `/public` ?

Actually, I would like to avoid having them generated in `/public` at all. I just don't want to have to commit them only for build. 

Thanks!

**Comment by JakiChen** [comment]
Hi，@Jeremboo 

**Yes, the program is configured to generate assets directly into the `publicDir` directory.**

1. _When using `yarn build`, the assets in `publicDir` will also be automatically copied to the `buildDir` directory by Astro;_
2. In order to preview the favicon changes on the browser during `yarn dev`, storing them in `publicDir` is currently the most effective way.
